# docker-compose.yml


services:
  db:
    image: postgres:15
    container_name: blogi_db
    restart: always
    environment:
      POSTGRES_USER: blogiuser
      POSTGRES_PASSWORD: blogipass
      POSTGRES_DB: blogi_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: blogi_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
